# Generated by Django 3.1.12 on 2022-02-14 22:16

from django.db import migrations, models
import djongo.models.fields
import process_text.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPair',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('pair_id', models.IntegerField()),
                ('source', djongo.models.fields.EmbeddedField(model_container=process_text.models.Text, model_form_class=process_text.models.TextForm)),
                ('translated', djongo.models.fields.EmbeddedField(model_container=process_text.models.Text, model_form_class=process_text.models.TextForm)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('translations', djongo.models.fields.ArrayField(model_container=process_text.models.TextPair, model_form_class=process_text.models.TextPairForm)),
            ],
        ),
    ]
