# Generated by Django 4.0.1 on 2022-02-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_text', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
